#############################################################################
# Makefile for building: vpn
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? 11? 21 22:59:25 2014
# Project:  vpn.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile vpn.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ilibs/tinyxml -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lcurl -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = about.cpp \
		imagelabel.cpp \
		linuxutils.cpp \
		location.cpp \
		logdialog.cpp \
		login.cpp \
		main.cpp \
		settings.cpp \
		server.cpp \
		statuswindow.cpp \
		systray.cpp \
		utils.cpp \
		libs/tinyxml/tinystr.cpp \
		libs/tinyxml/tinyxml.cpp \
		libs/tinyxml/tinyxmlerror.cpp \
		libs/tinyxml/tinyxmlparser.cpp moc_about.cpp \
		moc_imagelabel.cpp \
		moc_location.cpp \
		moc_logdialog.cpp \
		moc_login.cpp \
		moc_settings.cpp \
		moc_server.cpp \
		moc_statuswindow.cpp \
		moc_systray.cpp \
		qrc_vpn.cpp
OBJECTS       = about.o \
		imagelabel.o \
		linuxutils.o \
		location.o \
		logdialog.o \
		login.o \
		main.o \
		settings.o \
		server.o \
		statuswindow.o \
		systray.o \
		utils.o \
		tinystr.o \
		tinyxml.o \
		tinyxmlerror.o \
		tinyxmlparser.o \
		moc_about.o \
		moc_imagelabel.o \
		moc_location.o \
		moc_logdialog.o \
		moc_login.o \
		moc_settings.o \
		moc_server.o \
		moc_statuswindow.o \
		moc_systray.o \
		qrc_vpn.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		vpn.pro
QMAKE_TARGET  = vpn
DESTDIR       = 
TARGET        = vpn

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vpn.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile vpn.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile vpn.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vpn1.0.0 || $(MKDIR) .tmp/vpn1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vpn1.0.0/ && $(COPY_FILE) --parents about.h imagelabel.h linuxutils.h location.h logdialog.h login.h settings.h server.h statuswindow.h systray.h utils.h libs/tinyxml/tinystr.h libs/tinyxml/tinyxml.h .tmp/vpn1.0.0/ && $(COPY_FILE) --parents vpn.qrc .tmp/vpn1.0.0/ && $(COPY_FILE) --parents about.cpp imagelabel.cpp linuxutils.cpp location.cpp logdialog.cpp login.cpp main.cpp settings.cpp server.cpp statuswindow.cpp systray.cpp utils.cpp libs/tinyxml/tinystr.cpp libs/tinyxml/tinyxml.cpp libs/tinyxml/tinyxmlerror.cpp libs/tinyxml/tinyxmlparser.cpp .tmp/vpn1.0.0/ && (cd `dirname .tmp/vpn1.0.0` && $(TAR) vpn1.0.0.tar vpn1.0.0 && $(COMPRESS) vpn1.0.0.tar) && $(MOVE) `dirname .tmp/vpn1.0.0`/vpn1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vpn1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_about.cpp moc_imagelabel.cpp moc_location.cpp moc_logdialog.cpp moc_login.cpp moc_settings.cpp moc_server.cpp moc_statuswindow.cpp moc_systray.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about.cpp moc_imagelabel.cpp moc_location.cpp moc_logdialog.cpp moc_login.cpp moc_settings.cpp moc_server.cpp moc_statuswindow.cpp moc_systray.cpp
moc_about.cpp: about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

moc_imagelabel.cpp: imagelabel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imagelabel.h -o moc_imagelabel.cpp

moc_location.cpp: imagelabel.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		winutils.h \
		linuxutils.h \
		location.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) location.h -o moc_location.cpp

moc_logdialog.cpp: imagelabel.h \
		logdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) logdialog.h -o moc_logdialog.cpp

moc_login.cpp: login.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_settings.cpp: imagelabel.h \
		settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

moc_server.cpp: server.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) server.h -o moc_server.cpp

moc_statuswindow.cpp: utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h \
		login.h \
		location.h \
		logdialog.h \
		server.h \
		statuswindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) statuswindow.h -o moc_statuswindow.cpp

moc_systray.cpp: statuswindow.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h \
		login.h \
		location.h \
		logdialog.h \
		server.h \
		about.h \
		systray.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) systray.h -o moc_systray.cpp

compiler_rcc_make_all: qrc_vpn.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_vpn.cpp
qrc_vpn.cpp: vpn.qrc \
		images/flags/flag_libya.png \
		images/flags/flag_macau.png \
		images/flags/flag_mexico.png \
		images/flags/flag_wallis_and_futuna.png \
		images/flags/flag_congo_democratic_republic.png \
		images/flags/flag_norway.png \
		images/flags/flag_singapore.png \
		images/flags/flag_morocco.png \
		images/flags/flag_ecuador.png \
		images/flags/flag_rainbow.png \
		images/flags/flag_mozambique.png \
		images/flags/flag_algeria.png \
		images/flags/flag_niger.png \
		images/flags/flag_liechtenstein.png \
		images/flags/flag_colombia.png \
		images/flags/flag_lebanon.png \
		images/flags/flag_slovakia.png \
		images/flags/flag_moldova.png \
		images/flags/flag_israel.png \
		images/flags/flag_burundi.png \
		images/flags/flag_cambodia.png \
		images/log-copybutton.jpg \
		images/flags/flag_american_samoa.png \
		images/flags/flag_vietnam.png \
		images/flags/flag_saint_vincent_and_the_grenadines.png \
		images/flags/flag_argentina.png \
		images/log-contactbutton.jpg \
		images/flags/flag_rwanda.png \
		images/flags/flag_papua_new_guinea.png \
		images/flags/flag_cayman_islands.png \
		images/flags/flag_hong_kong.png \
		images/flags/flag_san_marino.png \
		images/flags/flag_bhutan.png \
		images/flags/flag_guatemala.png \
		images/flags/flag_anguilla.png \
		images/flags/flag_el_salvador.png \
		images/flags/flag_england.png \
		images/location-connect.jpg \
		images/flags/flag_lithuania.png \
		images/flags/flag_maldives.png \
		images/flags/flag_saint_pierre_and_miquelon.png \
		images/flags/flag_finland.png \
		images/flags/flag_new_zealand.png \
		images/flags/flag_kenya.png \
		images/flags/flag_british_indian_ocean_territory.png \
		images/flags/flag_generic.png \
		images/settings-bg.png \
		images/flags/flag_ireland.png \
		images/location-11.jpg \
		images/flags/flag_central_african_republic.png \
		images/flags/flag_monaco.png \
		images/flags/flag_kuwait.png \
		images/flags/flag_east_timor.png \
		images/tray-dis-red.jpg \
		images/flags/flag_wales.png \
		images/flags/flag_latvia.png \
		images/login-edit-border.jpg \
		images/flags/flag_british_virgin_islands.png \
		images/flags/flag_czech_republic.png \
		images/flags/flag_macedonia.png \
		images/location-settings.jpg \
		images/flags/flag_thailand.png \
		images/flags/flag_cote_divoire.png \
		images/flags/flag_vatican_city.png \
		images/login-btn.jpg \
		images/main2.png \
		images/flags/flag_sudan.png \
		images/flags/flag_venezuela.png \
		images/flags/flag_madagascar.png \
		images/flags/flag_suriname.png \
		images/flags/flag_south_georgia.png \
		images/img_safejumper.jpg \
		images/flags/flag_chile.png \
		images/tray-close-red.jpg \
		images/flags/flag_fiji.png \
		images/flags/flag_pakistan.png \
		images/tray-plug-red.jpg \
		images/flags/flag_martinique.png \
		images/flags/flag_costa_rica.png \
		images/img_connecting.png \
		images/flags/flag_mongolia.png \
		images/flags/flag_palau.png \
		images/title.png \
		images/flags/flag_burma.png \
		images/flags/flag_italy.png \
		images/flags/flag_bolivia.png \
		images/flags/flag_comoros.png \
		images/flags/flag_germany.png \
		images/flags/flag_pitcairn_islands.png \
		images/flags/flag_pirate.png \
		images/flags/flag_india.png \
		images/flags/flag_honduras.png \
		images/flags/flag_ghana.png \
		images/flags/flag_saint_kitts_and_nevis.png \
		images/flags/flag_ukraine.png \
		images/flags/flag_belize.png \
		images/flags/flag_guernsey.png \
		images/flags/flag_puerto_rico.png \
		images/flags/flag_greenland.png \
		images/flags/flag_somalia.png \
		images/flags/flag_nigeria.png \
		images/tray-global-red.jpg \
		images/flags/flag_tuvalu.png \
		images/flags/flag_virgin_islands.png \
		images/main-jump.jpg \
		images/flags/flag_bahamas.png \
		images/flags/flag_netherlands_antilles.png \
		images/flags/flag_poland.png \
		images/flags/flag_sao_tome_and_principe.png \
		images/flags/flag_equatorial_guinea.png \
		images/flags/flag_djibouti.png \
		images/flags/flag_malaysia.png \
		images/tray-attention-red.jpg \
		images/flags/flag_barbados.png \
		images/flags/flag_mauritius.png \
		images/flags/flag_brunei.png \
		images/mainstream.jpg \
		images/flags/flag_burkina_faso.png \
		images/flags/flag_norfolk_island.png \
		images/flags/flag_romania.png \
		images/flags/flag_vanuatu.png \
		images/flags/flag_canada.png \
		images/username.png \
		images/flags/flag_zimbabwe.png \
		images/tray-rocket-red.jpg \
		images/flags/flag_peru.png \
		images/flags/flag_zambia.png \
		images/flags/flag_usa.png \
		images/main1.png \
		images/flags/flag_dominican_republic.png \
		images/location-bg.png \
		images/login-bg.png \
		images/login-u.jpg \
		images/flags/flag_tanzania.png \
		images/img_qt.jpg \
		images/flags/flag_andorra.png \
		images/flags/flag_south_korea.png \
		images/mainip.jpg \
		images/flags/flag_antigua_and_barbuda.png \
		images/flags/flag_nepal.png \
		images/flags/flag_gabon.png \
		images/flags/flag_luxembourg.png \
		images/flags/flag_eritrea.png \
		images/flags/flag_cook_islands.png \
		images/flags/flag_tonga.png \
		images/flags/flag_falkland_islands.png \
		images/flags/flag_turkey.png \
		images/flags/flag_guinea_bissau.png \
		images/flags/flag_swaziland.png \
		images/flags/flag_spain.png \
		images/flags/flag_south_africa.png \
		images/tray-config-red.jpg \
		images/flags/flag_portugal.png \
		images/flags/flag_togo.png \
		images/flags/flag_checkered.png \
		images/flags/flag_congo_republic.png \
		images/flags/flag_iraq.png \
		images/flags/flag_niue.png \
		images/flags/flag_tunisia.png \
		images/flags/flag_cyprus.png \
		images/flags/flag_saudi_arabia.png \
		images/flags/flag_isle_of_man.png \
		images/flags/flag_cape_verde.png \
		images/flags/flag_denmark.png \
		images/mainlocation.jpg \
		images/flags/flag_faeroe_islands.png \
		images/location-21.jpg \
		images/flags/flag_croatia.png \
		images/mainwindow.jpg \
		images/flags/flag_saint_helena.png \
		images/flags/flag_france.png \
		images/flags/flag_jordan.png \
		images/location-arrow.jpg \
		images/flags/flag_tajikistan.png \
		images/passwd.png \
		images/flags/flag_slovenia.png \
		images/tray-mouse-red.jpg \
		images/flags/flag_belgium.png \
		images/settings-showlog.jpg \
		images/flags/flag_guam.png \
		images/flags/flag_georgia.png \
		images/flags/flag_scotland.png \
		images/flags/flag_austria.png \
		images/flags/flag_united_kingdom.png \
		images/tray-note-red.jpg \
		images/flags/flag_white.png \
		images/flags/flag_greece.png \
		images/flags/flag_samoa.png \
		images/img_connected.png \
		images/flags/flag_guyana.png \
		images/flags/flag_armenia.png \
		images/flags/flag_bangladesh.png \
		images/log-bg.png \
		images/tray-graph2-red.jpg \
		images/flags/flag_uganda.png \
		images/tray-help-red.jpg \
		images/flags/flag_uzbekistan.png \
		images/flags/flag_azerbaijan.png \
		images/flags/flag_eu.png \
		images/flags/flag_mali.png \
		images/flags/flag_malawi.png \
		images/location-check.jpg \
		images/flags/flag_bosnia_and_herzegovina.png \
		images/flags/flag_montserrat.png \
		images/flags/flag_uruguay.png \
		images/flags/flag_ethiopia.png \
		images/flags/flag_haiti.png \
		images/flags/flag_chad.png \
		images/flags/flag_netherlands.png \
		images/login-checkbox-unselected.jpg \
		images/flags/flag_grenada.png \
		images/flags/flag_senegal.png \
		images/flags/flag_liberia.png \
		images/img_disconnect.png \
		images/flags/flag_hungary.png \
		images/flags/flag_bermuda.png \
		images/flags/flag_saint_lucia.png \
		images/flags/flag_indonesia.png \
		images/flags/flag_japan.png \
		images/flags/flag_iran.png \
		images/flags/flag_malta.png \
		images/flags/flag_turkmenistan.png \
		images/flags/flag_panama.png \
		images/flags/flag_seychelles.png \
		images/flags/flag_sierra_leone.png \
		images/flags/flag_northern_mariana_islands.png \
		images/flags/flag_kyrgyzstan.png \
		images/flags/flag_jamaica.png \
		images/flags/flag_nauru.png \
		images/flags/flag_united_arab_emirates.png \
		images/flags/flag_north_korea.png \
		images/login-p.jpg \
		images/flags/flag_nicaragua.png \
		images/tray-icon-red.jpg \
		images/flags/flag_trinidad_and_tobago.png \
		images/flags/flag_kazakhstan.png \
		images/flags/flag_belarus.png \
		images/flags/flag_egypt.png \
		images/flags/flag_russia.png \
		images/flags/flag_bulgaria.png \
		images/flags/flag_china.png \
		images/flags/flag_estonia.png \
		images/flags/flag_jersey.png \
		images/flags/flag_gambia.png \
		images/flags/flag_namibia.png \
		images/flags/flag_marshall_islands.png \
		images/settings-update.jpg \
		images/flags/flag_botswana.png \
		images/flags/flag_philippines.png \
		images/flags/flag_french_polynesia.png \
		images/flags/flag_bahrain.png \
		images/flags/flag_micronesia.png \
		images/flags/flag_sri_lanka.png \
		images/flags/flag_mauritania.png \
		images/flags/flag_albania.png \
		images/flags/flag_afghanistan.png \
		images/flags/flag_turks_and_caicos_islands.png \
		images/flags/flag_qatar.png \
		images/flags/flag_lesotho.png \
		images/flags/flag_benin.png \
		images/flags/flag_serbia.png \
		images/flags/flag_cuba.png \
		images/flags/flag_aruba.png \
		images/flags/flag_guinea.png \
		images/img_openvpn.jpg \
		images/flags/flag_montenegro.png \
		images/flags/flag_australia.png \
		images/flags/flag_yemen.png \
		images/flags/flag_kiribati.png \
		images/login-checkbox-selected.jpg \
		images/flags/flag_gibraltar.png \
		images/main-connect.jpg \
		images/flags/flag_brazil.png \
		images/flags/flag_cameroon.png \
		images/flags/flag_solomon_islands.png \
		images/flags/flag_laos.png \
		images/vc.ico \
		images/flags/flag_iceland.png \
		images/flags/flag_syria.png \
		images/main-settings.jpg \
		images/flags/flag_sweden.png \
		images/tray-info-red.jpg \
		images/flags/flag_paraguay.png \
		images/location-22.jpg \
		images/flags/flag_angola.png \
		images/flags/flag_switzerland.png \
		images/flags/flag_dominica.png \
		images/flags/flag_oman.png
	/usr/bin/rcc -name vpn vpn.qrc -o qrc_vpn.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

about.o: about.cpp about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

imagelabel.o: imagelabel.cpp imagelabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagelabel.o imagelabel.cpp

linuxutils.o: linuxutils.cpp linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linuxutils.o linuxutils.cpp

location.o: location.cpp location.h \
		imagelabel.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		winutils.h \
		linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o location.o location.cpp

logdialog.o: logdialog.cpp logdialog.h \
		imagelabel.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		winutils.h \
		linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logdialog.o logdialog.cpp

login.o: login.cpp login.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

main.o: main.cpp systray.h \
		statuswindow.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h \
		login.h \
		location.h \
		logdialog.h \
		server.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

settings.o: settings.cpp settings.h \
		imagelabel.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		winutils.h \
		linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

server.o: server.cpp server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

statuswindow.o: statuswindow.cpp statuswindow.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h \
		login.h \
		location.h \
		logdialog.h \
		server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statuswindow.o statuswindow.cpp

systray.o: systray.cpp systray.h \
		statuswindow.h \
		utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h \
		login.h \
		location.h \
		logdialog.h \
		server.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systray.o systray.cpp

utils.o: utils.cpp utils.h \
		libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h \
		settings.h \
		imagelabel.h \
		winutils.h \
		linuxutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

tinystr.o: libs/tinyxml/tinystr.cpp libs/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinystr.o libs/tinyxml/tinystr.cpp

tinyxml.o: libs/tinyxml/tinyxml.cpp libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml.o libs/tinyxml/tinyxml.cpp

tinyxmlerror.o: libs/tinyxml/tinyxmlerror.cpp libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlerror.o libs/tinyxml/tinyxmlerror.cpp

tinyxmlparser.o: libs/tinyxml/tinyxmlparser.cpp libs/tinyxml/tinyxml.h \
		libs/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlparser.o libs/tinyxml/tinyxmlparser.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_imagelabel.o: moc_imagelabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagelabel.o moc_imagelabel.cpp

moc_location.o: moc_location.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_location.o moc_location.cpp

moc_logdialog.o: moc_logdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logdialog.o moc_logdialog.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_statuswindow.o: moc_statuswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statuswindow.o moc_statuswindow.cpp

moc_systray.o: moc_systray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systray.o moc_systray.cpp

qrc_vpn.o: qrc_vpn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_vpn.o qrc_vpn.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

